models:
  - name: "Qwen/Qwen3-1.7B"
    short: "qwen3-1.7b"

option_columns: ["choice_A", "choice_B", "choice_C", "choice_D"]
option_letters: ["A", "B", "C", "D"]

trim_versions:
  0: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/pre_results_compelete_llama_4_maverik_arc_challenge.csv"
  90: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_90.csv"
  80: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_80.csv"
  70: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_70.csv"
  60: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_60.csv"
  50: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_50.csv"
  40: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_40.csv"
  30: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_30.csv"
  20: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_20.csv"
  10: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_maverik/concise_rewrites_llama-4-maverick_10.csv"

results_dir: "/home/a_zahedzadeh/self-explaination-thesis/results/models/evaluation/qwen_1.7B/en/llama"
filename_pattern: "eval_llama_4_maverik_masked_{pct}.csv"