models:
  - name: "google/gemma-3-4b-pt"
    short: "gemma3-4b-pt"
  - name: "meta-llama/Llama-3.2-3B"
    short: "llama-3.2-3b"

option_columns: ["choice_A", "choice_B", "choice_C", "choice_D"]
option_letters: ["A", "B", "C", "D"]

trim_versions:
  0: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/pre_results_compelete_cohere_command_r_arc_challenge.csv"
  90: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_90.csv"
  80: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_80.csv"
  70: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_70.csv"
  60: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_60.csv"
  50: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_50.csv"
  40: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_40.csv"
  30: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_30.csv"
  20: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_20.csv"
  10: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/cohere_r_command/en/concise_rewrites_command-r-08-2024_10.csv"

# Base directory (script will automatically create subfolders per model)
results_dir: "/home/a_zahedzadeh/self-explaination-thesis/results/models/evaluation"

# Supports {model} and {pct}
filename_pattern: "eval_cohere-r_{model}_{pct}.csv"