models:
  - name: "google/gemma-3-4b-pt"
    short: "gemma3-4b-pt"
  - name: "meta-llama/Llama-3.2-3B"
    short: "llama-3.2-3b"

option_columns: ["choice_A", "choice_B", "choice_C", "choice_D"]
option_letters: ["A", "B", "C", "D"]

trim_versions:
  0: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/pre_results_compelete_llama_4_scout_arc_challenge.csv"
  90: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_90.csv"
  80: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_80.csv"
  70: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_70.csv"
  60: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_60.csv"
  50: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_50.csv"
  40: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_40.csv"
  30: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_30.csv"
  20: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_20.csv"
  10: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/llama_4_scout/en/concise_rewrites_llama-4-scout_10.csv"

# Base directory (script will automatically create subfolders per model)
results_dir: "/home/a_zahedzadeh/self-explaination-thesis/results/models/evaluation"

# Supports {model} and {pct}
filename_pattern: "eval_llama-4-scout_{model}_{pct}.csv"