api_key: "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"
model: "anthropic/claude-3-haiku"

# Dataset input
input: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/claude_3_haiku/fa/pre_results_compelete_claude_3_haiku_arc_challenge_fa.csv"

# Output settings
save_dir: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/claude_3_haiku/fa"
save_prefix: "concise_rewrites_claude_3_haiku_fa"   # final file â†’ {save_prefix}_{pct}.csv

# Model generation settings
temperature: 0.3
percentages: [70, 60, 50, 40]
sleep_seconds: 0.7

# Logging
log_level: "INFO"
