input: /home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/claude_3_haiku/pre_results_compelete_claude_3_haiku_arc_challenge.csv
output_dir: /home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/claude_3_haiku
api_key: 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
model: anthropic/claude-3-haiku
model_name: claude-3-haiku
percentages: [90, 80, 70, 60, 50, 40, 30, 20, 10]
log_level: INFO
sleep: 1.2
