api_key: "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"
model: "cohere/command-r-08-2024"

# Dataset input
input: "/home/tmptiloct15/self-explaination-thesis/results/models/prediction/cohere_r_command/fa/pre_results_compelete_cohere_command_r_arc_challenge_fa.csv"

# Output settings
save_dir: "/home/tmptiloct15/self-explaination-thesis/results/models/prediction/cohere_r_command/fa"
save_prefix: "concise_rewrites_cohere_r_command_fa"   # final file â†’ {save_prefix}_{pct}.csv

# Model generation settings
temperature: 0.3
percentages: [90, 80, 70, 60, 50, 40, 30, 20, 10]
sleep_seconds: 0.7

# Logging
log_level: "INFO"
