api_key: "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"
model: "mistralai/mistral-small-3.1-24b-instruct"

# ───── Input / Output ─────
input: "../data/processed/ai2_arc/ARC-Challenge-clean(persian).csv"
save_dir: "/home/tmptiloct15/self-explaination-thesis/results/models/prediction/mistral_small_3.1/fa"
save_name: "pre_results_compelete_mistral_small_3.1_arc_challenge_fa.csv"

temperature: 0.3
max_tokens: None
log_level: "INFO"
system_prompt: |
  You are a reasoning assistant for Persian multiple-choice Question Answering.
  Always answer following the strict XML format.
  The explanation MUST be in Persian, while prediction must remain a single letter (A/B/C/D).
sleep_seconds: 0.7  