models:
  - name: "google/gemma-3-4b-pt"
    short: "gemma3-4b-pt"
  - name: "meta-llama/Llama-3.2-3B"
    short: "llama-3.2-3b"

option_columns: ["choice_A", "choice_B", "choice_C", "choice_D"]
option_letters: ["A", "B", "C", "D"]

trim_versions:
  0: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/pre_results_compelete_gemini_2_flash_arc_challenge_fa.csv"
  90: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_90.csv"
  80: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_80.csv"
  70: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_70.csv"
  60: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_60.csv"
  50: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_50.csv"
  40: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_40.csv"
  30: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_30.csv"
  20: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_20.csv"
  10: "/home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/gemini_2_flash/fa/concise_rewrites_gemini-2.0-flash-001_fa_10.csv"

results_dir: "/home/a_zahedzadeh/self-explaination-thesis/results/models/evaluation/qwen_1.7B/fa/gemini_2_flash"
filename_pattern: "eval_gemini_2.0_flash_fa_{pct}.csv"


