input: /home/tmptiloct15/self-explaination-thesis/results/models/prediction/cohere_r_command/en/pre_results_compelete_cohere_command_r_arc_challenge.csv
output_dir: /home/tmptiloct15/self-explaination-thesis/results/models/prediction/cohere_r_command/en
api_key: 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
model: cohere/command-r-08-2024
model_name: command-r-08-2024
percentages: [90, 80, 70, 60, 50, 40, 30, 20, 10]
log_level: INFO
sleep: 1.2
