model: "mistralai/mistral-small-3.1-24b-instruct"
input: "../data/processed/ai2_arc/ARC-Challenge-clean.csv"
output: "pre_results_compelete_mistrall_3.1_small_arc_challenge.csv"
temperature: 0.3
max_tokens: None
log_level: "INFO"
system_prompt: |
  You are a reasoning assistant for multiple-choice Question Answering.
  Always respond in this exact format:

  <prediction>[Your choice A/B/C/D]</prediction>
  <explanation>[Your explanation]</explanation>
