input: /home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/grok_3_mini/en/pre_results_compelete_grok_3_mini_arc_challenge.csv
output_dir: /home/a_zahedzadeh/self-explaination-thesis/results/models/prediction/grok_3_mini/en
api_key: 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
model: x-ai/grok-3-mini
model_name: grok-3-mini
percentages: [90, 80, 70, 60, 50, 40, 30, 20, 10]
log_level: INFO
sleep: 1.4
